services:
  api:
    build: .
    container_name: katiho_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    expose:
      - "8000"
    networks:
      - global_web
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=global_web"

      - "traefik.http.routers.katiho-api.rule=Host(`api.katiho.milanprajapati.com.np`)"
      - "traefik.http.routers.katiho-api.entrypoints=websecure"
      - "traefik.http.routers.katiho-api.tls=true"
      - "traefik.http.routers.katiho-api.tls.certresolver=letsencrypt"

      - "traefik.http.services.katiho-api.loadbalancer.server.port=8000"

  worker:
    build: .
    container_name: katiho_worker
    command: celery -A app.celery.celery_app.celery_app worker --loglevel=info
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - internal

  beat:
    build: .
    container_name: katiho_beat
    command: celery -A app.celery.celery_app.celery_app beat --loglevel=info
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: katiho_redis
    restart: unless-stopped
    networks:
      - internal

networks:
  global_web:
    external: true

  internal:
    driver: bridge