"""add image url and discounted price to products

Revision ID: cbd3a92794ed
Revises: d8f91141732f
Create Date: 2026-07-15 14:10:45.893640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd3a92794ed'
down_revision: Union[str, Sequence[str], None] = 'd8f91141732f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discounted_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'discounted_price')
    # ### end Alembic commands ###
